"use client";

import { useEffect, useState } from "react";

type RCAResponse = {
  root_cause: string;
  impact: string;
  affected_endpoints: string[];
  recommended_actions: string[];
  risk_level: "low" | "medium" | "high" | "critical";
  confidence: number;
};

export default function RCAPage() {
  const [rca, setRca] = useState<RCAResponse | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch("http://localhost:8000/anomalies/rca?testing=true", {
        method: "POST",
    })
        .then((res) => res.json())
        .then((data) => {
        setRca(data.rca);
        setLoading(false);
        })
        .catch(() => setLoading(false));
    }, []);


  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center text-slate-500">
        Running AI Root Cause Analysis…
      </div>
    );
  }

  if (!rca) {
    return (
      <div className="min-h-screen flex items-center justify-center text-red-500">
        Failed to load RCA report
      </div>
    );
  }

  const riskColor = {
    low: "bg-green-600",
    medium: "bg-yellow-500",
    high: "bg-orange-600",
    critical: "bg-red-600",
  }[rca.risk_level];

  return (
    <div className="min-h-screen bg-slate-100 p-8">
      <div className="max-w-7xl mx-auto space-y-8">

        {/* HEADER */}
        <h1 className="text-3xl font-semibold text-slate-900">
          RCA Analysis <span className="text-slate-500 font-normal">AI-Generated Report</span>
        </h1>

        {/* TOP STATS */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className={`rounded-xl p-6 text-white ${riskColor}`}>
            <p className="text-sm opacity-80">Risk Level</p>
            <p className="text-2xl font-semibold uppercase">
              {rca.risk_level}
            </p>
          </div>

          <div className="rounded-xl p-6 bg-emerald-600 text-white">
            <p className="text-sm opacity-80">Confidence</p>
            <p className="text-2xl font-semibold">
              {(rca.confidence * 100).toFixed(0)}%
            </p>
          </div>

          <div className="rounded-xl p-6 bg-slate-800 text-white">
            <p className="text-sm opacity-80">Analysis Scope</p>
            <p className="text-2xl font-semibold">
              AI-Correlated Logs
            </p>
          </div>
        </div>

        {/* MAIN GRID */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">

          {/* LEFT PANEL */}
          <div className="lg:col-span-2 space-y-6">

            {/* ROOT CAUSE */}
            <Section title="Root Cause">
              {rca.root_cause}
            </Section>

            {/* IMPACT */}
            <Section title="Impact">
              {rca.impact}
            </Section>

            {/* AFFECTED ENDPOINTS */}
            <Section title="Affected Components">
              <div className="flex flex-wrap gap-3">
                {rca.affected_endpoints.map((ep, i) => (
                  <span
                    key={i}
                    className="px-4 py-2 rounded-full bg-slate-200 text-sm text-slate-700"
                  >
                    {ep}
                  </span>
                ))}
              </div>
            </Section>

            {/* RECOMMENDED ACTIONS */}
            <Section title="Recommended Actions">
              <ul className="list-disc pl-5 space-y-2 text-slate-700">
                {rca.recommended_actions.map((a, i) => (
                  <li key={i}>{a}</li>
                ))}
              </ul>
            </Section>
          </div>

          {/* RIGHT PANEL */}
          <div className="space-y-6">
            <div className="rounded-xl border bg-white p-6">
              <h3 className="font-semibold text-slate-900 mb-3">
                AI Assessment Notes
              </h3>
              <p className="text-sm text-slate-600">
                This analysis is generated by correlating recent anomalies,
                error patterns, and failing endpoints using an LLM-based
                reasoning engine.
              </p>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="rounded-xl border bg-white p-6">
      <h2 className="font-semibold text-slate-900 mb-3">{title}</h2>
      <p className="text-slate-700 leading-relaxed">{children}</p>
    </div>
  );
}
